- api/src/main/java/org/openmrs/module/ipd/api/dao/ScheduleDAO.java
- api/src/main/java/org/openmrs/module/ipd/api/dao/impl/HibernateScheduleDAO.java
- api/src/main/java/org/openmrs/module/ipd/api/service/ScheduleService.java
- api/src/main/java/org/openmrs/module/ipd/api/service/impl/ScheduleServiceImpl.java
- api/src/test/java/org/openmrs/module/ipd/api/dao/impl/HibernateScheduleDAOIntegrationTest.java
- api/src/test/java/org/openmrs/module/ipd/api/service/impl/ScheduleServiceImplTest.java
- omod/src/main/java/org/openmrs/module/ipd/contract/ScheduleMedicationResponse.java
- omod/src/main/java/org/openmrs/module/ipd/controller/IPDScheduleController.java
- omod/src/main/java/org/openmrs/module/ipd/service/IPDScheduleService.java
- omod/src/main/java/org/openmrs/module/ipd/service/impl/IPDScheduleServiceImpl.java
JIRA - https://bahmni.atlassian.net/jira/software/c/projects/BAH/boards/55?modal=detail&selectedIssue=BAH-3157
Asana - https://app.asana.com/0/1204322126657135/1204950368410826
This PR has changes to add a new endpoint that will help to fetch the schedules of a patient in full or for certain orders.
> Arjun | BAH-3157 | Fetch Schedules for orders

- .github/workflows/build_publish.yaml
Asana - https://app.asana.com/0/1204322126657135/1206085816519258
Changes to deploy ipd omod on merge to Bahmni-IPD-master branch
> A-1206085816519258 | Automate IPD omod deployment to QA and UAT environments

- .github/workflows/build_publish.yaml
- .mvn/wrapper/maven-wrapper.properties
- mvnw
- mvnw.cmd
Had to use mvn instead of wrapper as it was throwing errors in the workflow
> Arjun | Fix deployment workflow

- api/src/main/java/org/openmrs/module/ipd/api/dao/SlotDAO.java
- api/src/main/java/org/openmrs/module/ipd/api/dao/impl/HibernateSlotDAO.java
- api/src/main/java/org/openmrs/module/ipd/api/service/SlotService.java
- api/src/main/java/org/openmrs/module/ipd/api/service/impl/SlotServiceImpl.java
- omod/src/main/java/org/openmrs/module/ipd/controller/IPDScheduleController.java
- omod/src/main/java/org/openmrs/module/ipd/service/IPDScheduleService.java
- omod/src/main/java/org/openmrs/module/ipd/service/impl/IPDScheduleServiceImpl.java
Asana: https://app.asana.com/0/1204322126657135/1206156796138532/f
> A-1206156796138532 | Abi | add. shift navigation functionality in Nursing tasks display control

- omod/src/main/java/org/openmrs/module/ipd/contract/MedicationAdministrationRequest.java
- omod/src/main/java/org/openmrs/module/ipd/contract/ScheduleMedicationRequest.java
- omod/src/main/java/org/openmrs/module/ipd/factory/MedicationAdministrationFactory.java
- omod/src/main/java/org/openmrs/module/ipd/service/impl/IPDMedicationAdministrationServiceImpl.java
- creates schedule while saving adhoc tasks when there is no active schedule
- refactors contract for medication request for doseUnits, route and site
JIRA : [BAH-3460](https://bahmni.atlassian.net/browse/BAH-3460)
> BAH-3460 | Kavitha | refactor save adhoc medications

- api/src/main/java/org/openmrs/module/ipd/api/model/Slot.java
- omod/src/main/java/org/openmrs/module/ipd/postprocessor/IPDTransactionHandler.java
- omod/src/main/java/org/openmrs/module/ipd/service/IPDScheduleService.java
- omod/src/main/java/org/openmrs/module/ipd/service/impl/IPDScheduleServiceImpl.java
Changes to stop/void slots associated with drugorder when its stopped
> Changes to stop/void slots associated with drugorder when its stopped

- api/src/main/java/org/openmrs/module/ipd/api/dao/SlotDAO.java
- api/src/main/java/org/openmrs/module/ipd/api/dao/impl/HibernateSlotDAO.java
- api/src/main/java/org/openmrs/module/ipd/api/model/Slot.java
- api/src/main/java/org/openmrs/module/ipd/api/service/SlotService.java
- api/src/main/java/org/openmrs/module/ipd/api/service/impl/SlotServiceImpl.java
- omod/src/main/java/org/openmrs/module/ipd/contract/DrugOrderScheduleResponse.java
- omod/src/main/java/org/openmrs/module/ipd/contract/MedicationSlotResponse.java
- omod/src/main/java/org/openmrs/module/ipd/controller/IPDScheduleController.java
- omod/src/main/java/org/openmrs/module/ipd/factory/SlotFactory.java
- omod/src/main/java/org/openmrs/module/ipd/model/DrugOrderSchedule.java
- omod/src/main/java/org/openmrs/module/ipd/service/IPDScheduleService.java
- omod/src/main/java/org/openmrs/module/ipd/service/impl/IPDMedicationAdministrationServiceImpl.java
- omod/src/main/java/org/openmrs/module/ipd/service/impl/IPDScheduleServiceImpl.java
Asana: https://app.asana.com/0/1204322126657135/1206294050497134/f
> Nursing task enhancement

- omod/src/main/java/org/openmrs/module/ipd/service/impl/SlotTimeCreationService.java
- refactored slot creation logic so that it would create slots based on the incoming fixed frequency schedules
> Kavitha | fix slot creation logic for 1 day

- omod/src/main/java/org/openmrs/module/ipd/service/impl/IPDScheduleServiceImpl.java
Asana: https://app.asana.com/0/1204322126657135/1206389781267740/f
> Abi | update. status as Stopped once administered and stopped a medicine

- api/src/main/java/org/openmrs/module/ipd/api/dao/SlotDAO.java
- api/src/main/java/org/openmrs/module/ipd/api/dao/impl/HibernateSlotDAO.java
- api/src/main/java/org/openmrs/module/ipd/api/model/ServiceType.java
- api/src/main/java/org/openmrs/module/ipd/api/service/impl/SlotServiceImpl.java
- api/src/main/resources/liquibase.xml
- api/src/test/java/org/openmrs/module/ipd/api/dao/impl/HibernateSlotDAOIntegrationTest.java
- omod/src/main/java/org/openmrs/module/ipd/contract/ScheduleMedicationRequest.java
- omod/src/main/java/org/openmrs/module/ipd/controller/IPDScheduleController.java
- omod/src/main/java/org/openmrs/module/ipd/factory/SlotFactory.java
- omod/src/main/java/org/openmrs/module/ipd/service/impl/IPDScheduleServiceImpl.java
https://app.asana.com/0/1204322126657135/1206484766430736
Changes to accommodate PRN PlaceHolder card in Fetch Slots API and also create placeholder card for PRN
> API to save/schedule the placeholder Tasks for PRN

- omod/src/main/java/org/openmrs/module/ipd/contract/DrugOrderScheduleResponse.java
condition added to check if slot start time is after current time
> condition added to check if slot start time is after current time

- omod/src/main/java/org/openmrs/module/ipd/contract/DrugOrderScheduleResponse.java
get the pending slots after the current time in drug order schedule response
> [Sri/kalai] - get the pending slots after the current time in drug order schedule response

- omod/src/main/java/org/openmrs/module/ipd/controller/IPDScheduleController.java
- omod/src/main/java/org/openmrs/module/ipd/service/impl/IPDScheduleServiceImpl.java
Change to consider MedicationRequest as a default serviceType if is not sent in payload
> Change to consider MedicationRequest as a default serviceType if is not sent in payload

- api/src/main/java/org/openmrs/module/ipd/api/dao/SlotDAO.java
- api/src/main/java/org/openmrs/module/ipd/api/dao/impl/HibernateSlotDAO.java
- api/src/main/java/org/openmrs/module/ipd/api/service/SlotService.java
- api/src/main/java/org/openmrs/module/ipd/api/service/impl/SlotServiceImpl.java
- api/src/test/java/org/openmrs/module/ipd/api/dao/impl/HibernateSlotDAOIntegrationTest.java
- api/src/test/java/org/openmrs/module/ipd/api/service/impl/SlotServiceImplTest.java
- api/src/test/resources/scheduleMedicationsTestData.xml
- omod/src/main/java/org/openmrs/module/ipd/contract/PatientMedicationSummaryResponse.java
- omod/src/main/java/org/openmrs/module/ipd/contract/PrescribedOrderSlotSummaryResponse.java
- omod/src/main/java/org/openmrs/module/ipd/controller/IPDScheduleController.java
- omod/src/main/java/org/openmrs/module/ipd/model/PatientMedicationSummary.java
- omod/src/main/java/org/openmrs/module/ipd/model/PrescribedOrderSlotSummary.java
- omod/src/main/java/org/openmrs/module/ipd/service/IPDScheduleService.java
- omod/src/main/java/org/openmrs/module/ipd/service/impl/IPDScheduleServiceImpl.java
JIRA ref: [BAH-3600](https://bahmni.atlassian.net/browse/BAH-3600)
Asana link: https://app.asana.com/0/1204322126657135/1206514083860608/f
> Kavitha | add api to fetch slots by patient list with custom includes

- api/src/main/java/org/openmrs/module/ipd/api/dao/WardDAO.java
- api/src/main/java/org/openmrs/module/ipd/api/dao/impl/HibernateWardDAO.java
- api/src/main/java/org/openmrs/module/ipd/api/model/AdmittedPatient.java
- api/src/main/java/org/openmrs/module/ipd/api/service/WardService.java
- api/src/main/java/org/openmrs/module/ipd/api/service/impl/WardServiceImpl.java
- api/src/test/java/org/openmrs/module/ipd/api/dao/impl/HibernateWardDAOIntegrationTest.java
- api/src/test/resources/WardDAOTestData.xml
- omod/src/main/java/org/openmrs/module/ipd/contract/AdmittedPatientResponse.java
- omod/src/main/java/org/openmrs/module/ipd/controller/IPDWardController.java
- omod/src/main/java/org/openmrs/module/ipd/service/IPDWardService.java
- omod/src/main/java/org/openmrs/module/ipd/service/impl/IPDWardServiceImpl.java
Search functionality API added & Refactor get patients API
> Search functionality API added & Refactor get patients API

- omod/src/main/java/org/openmrs/module/ipd/contract/DrugOrderScheduleResponse.java
Add boolean key to show if all slots are attended
> Add boolean key to show if all slots are attended

- omod/src/main/java/org/openmrs/module/ipd/service/impl/SlotTimeCreationService.java
JIRA ref : [BAH-3651](https://bahmni.atlassian.net/browse/BAH-3651)
> Kavitha | refactored slot creation logic for continuous medication

- api/src/main/java/org/openmrs/module/ipd/api/dao/CareTeamDAO.java
- api/src/main/java/org/openmrs/module/ipd/api/dao/impl/HibernateCareTeamDAO.java
- api/src/main/java/org/openmrs/module/ipd/api/dao/impl/HibernateWardDAO.java
- api/src/main/java/org/openmrs/module/ipd/api/model/AdmittedPatient.java
- api/src/main/java/org/openmrs/module/ipd/api/model/CareTeam.java
- api/src/main/java/org/openmrs/module/ipd/api/model/CareTeamParticipant.java
- api/src/main/java/org/openmrs/module/ipd/api/service/CareTeamService.java
- api/src/main/java/org/openmrs/module/ipd/api/service/impl/CareTeamServiceImpl.java
- api/src/main/java/org/openmrs/module/ipd/api/util/DateTimeUtil.java
- api/src/main/resources/liquibase.xml
- api/src/test/java/org/openmrs/module/ipd/api/dao/impl/HibernateCareTeamDAOIntegrationTest.java
- api/src/test/java/org/openmrs/module/ipd/api/service/impl/CareTeamServiceImplTest.java
- api/src/test/resources/CareTeamDAOTestData.xml
- omod/src/main/java/org/openmrs/module/ipd/contract/CareTeamParticipantRequest.java
- omod/src/main/java/org/openmrs/module/ipd/contract/CareTeamParticipantResponse.java
- omod/src/main/java/org/openmrs/module/ipd/contract/CareTeamRequest.java
- omod/src/main/java/org/openmrs/module/ipd/contract/CareTeamResponse.java
- omod/src/main/java/org/openmrs/module/ipd/contract/DrugOrderScheduleResponse.java
- omod/src/main/java/org/openmrs/module/ipd/controller/IPDCareTeamController.java
- omod/src/main/java/org/openmrs/module/ipd/factory/CareTeamFactory.java
- omod/src/main/java/org/openmrs/module/ipd/service/IPDCareTeamService.java
- omod/src/main/java/org/openmrs/module/ipd/service/impl/IPDCareTeamServiceImpl.java
Bookmarking API - API To Create Care Team & its Participants
> Bookmarking API - API To Create Care Team & its Participants

- api/src/main/java/org/openmrs/module/ipd/api/dao/impl/HibernateWardDAO.java
CareTeam info added to search API as well
> CareTeam info added to search API as well

- api/src/main/java/org/openmrs/module/ipd/api/dao/impl/HibernateWardDAO.java
Removed CareTeam Particpants join condition
> Removed CareTeam Particpants join condition

- api/src/main/java/org/openmrs/module/ipd/api/dao/WardDAO.java
- api/src/main/java/org/openmrs/module/ipd/api/dao/impl/HibernateWardDAO.java
- api/src/main/java/org/openmrs/module/ipd/api/model/WardPatientsSummary.java
- api/src/main/java/org/openmrs/module/ipd/api/service/WardService.java
- api/src/main/java/org/openmrs/module/ipd/api/service/impl/WardServiceImpl.java
- omod/src/main/java/org/openmrs/module/ipd/contract/IPDWardPatientSummaryResponse.java
- omod/src/main/java/org/openmrs/module/ipd/controller/IPDWardController.java
- omod/src/main/java/org/openmrs/module/ipd/service/IPDWardService.java
- omod/src/main/java/org/openmrs/module/ipd/service/impl/IPDWardServiceImpl.java
https://app.asana.com/0/home/1204411156764690/1206860834641287
> A-1206860834641287 | API Changes to show count of myPatients

- api/src/main/java/org/openmrs/module/ipd/api/dao/impl/HibernateWardDAO.java
- api/src/main/resources/liquibase.xml
BugFixes for IPD2 Release | Add filters to orders & changed time of Mark Missed Job
> BugFixes for IPD2 Release | Add filters to orders & changed time of Mark Missed Job

- omod/src/main/java/org/openmrs/module/ipd/service/impl/IPDVisitServiceImpl.java
Changes to Show the medication of Immediate Previous Visit Only if it is an OPD Visit
> Changes to Show the medication of Immediate Previous Visit Only if it is an OPD Visit

- api/src/main/java/org/openmrs/module/ipd/api/events/handler/impl/RolloverTaskEventHandler.java
- pom.xml
Upgrade Fhir2 version & Fhir2 Extension Version
> Upgrade Fhir2 version & Fhir2 Extension Version

- api/src/main/java/org/openmrs/module/ipd/api/dao/impl/HibernateWardDAO.java
- omod/src/main/resources/config.xml
- supports search of patients with multiple words in the care view dashboard
- updates module description
> Kavitha| refactored search to support multiple words

- api/src/main/java/org/openmrs/module/ipd/api/dao/impl/HibernateWardDAO.java
https://app.asana.com/0/1204322126657135/1207646706060470
> A-1207646706060470 | New treatments to be scheduled' is displayed to the Nurses when they do not have a treatment

- LICENSE
- pom.xml
This PR updates the LICENSE of the repository from AGPL to MPLv2 with Healthcare Disclaimer
> BAH-4073 | Refactor. Change LICENSE to OMRS MPLv2

- .github/workflows/build_publish.yaml
- .github/workflows/release_deploy.yml
- .github/workflows/validate_pr.yml
- omod/src/main/resources/config.xml
- omod/src/test/resources/config.xml
- pom.xml
This PR adds a workflow to release artifacts on push of a tag.
Also, fix has been added to read module properties in config.xml from the project's pom.xml
> BAH-4093 | Add. Workflow to release artifacts on push of a tag
